-- Update currency labels to Thai baht and add employee order workflow labels.

INSERT INTO translations (key, locale, value) VALUES
  ('admin.price_per_kg', 'en', 'Price / kg (THB)'),
  ('admin.flat_fee', 'en', 'Flat Fee (THB)'),
  ('admin.minimum_charge', 'en', 'Minimum (THB)'),
  ('employee.open_camera', 'en', 'Open camera'),
  ('employee.stop_camera', 'en', 'Stop camera'),
  ('employee.scan_manual', 'en', 'Scanner input also works here'),
  ('employee.camera_unavailable', 'en', 'Camera access is unavailable'),
  ('employee.open_order', 'en', 'Open / Edit'),
  ('employee.edit_order', 'en', 'Edit Order'),
  ('employee.edit_status', 'en', 'Edit Status'),
  ('employee.back_dashboard', 'en', 'Back to Dashboard'),
  ('employee.order_saved', 'en', 'Order saved'),
  ('employee.order_edit_error', 'en', 'Check the order details and try again'),
  ('print.print_all', 'en', 'Print Receipt + Label'),

  ('admin.price_per_kg', 'he', 'מחיר / ק"ג (באט)'),
  ('admin.flat_fee', 'he', 'תשלום קבוע (באט)'),
  ('admin.minimum_charge', 'he', 'מינימום (באט)'),
  ('employee.open_camera', 'he', 'פתח מצלמה'),
  ('employee.stop_camera', 'he', 'עצור מצלמה'),
  ('employee.scan_manual', 'he', 'אפשר גם לסרוק עם אקדח ברקוד במסך הזה'),
  ('employee.camera_unavailable', 'he', 'אין גישה למצלמה'),
  ('employee.open_order', 'he', 'פתח / ערוך'),
  ('employee.edit_order', 'he', 'עריכת הזמנה'),
  ('employee.edit_status', 'he', 'עריכת סטטוס'),
  ('employee.back_dashboard', 'he', 'חזרה ללוח העבודה'),
  ('employee.order_saved', 'he', 'ההזמנה נשמרה'),
  ('employee.order_edit_error', 'he', 'בדוק את פרטי ההזמנה ונסה שוב'),
  ('print.print_all', 'he', 'הדפס קבלה ותווית'),

  ('admin.price_per_kg', 'my', 'ကီလိုနှုန်း ဈေး (THB)'),
  ('admin.flat_fee', 'my', 'ပုံသေကြေး (THB)'),
  ('admin.minimum_charge', 'my', 'အနည်းဆုံး (THB)'),
  ('employee.open_camera', 'my', 'ကင်မရာ ဖွင့်မည်'),
  ('employee.stop_camera', 'my', 'ကင်မရာ ရပ်မည်'),
  ('employee.scan_manual', 'my', 'ဘားကုဒ်စကင်နာ ဖြင့်လည်း စကင်နိုင်သည်'),
  ('employee.camera_unavailable', 'my', 'ကင်မရာ အသုံးပြုမရပါ'),
  ('employee.open_order', 'my', 'ဖွင့် / ပြင်မည်'),
  ('employee.edit_order', 'my', 'အမှာ ပြင်မည်'),
  ('employee.edit_status', 'my', 'အခြေအနေ ပြင်မည်'),
  ('employee.back_dashboard', 'my', 'အလုပ်မျက်နှာပြင်သို့ ပြန်မည်'),
  ('employee.order_saved', 'my', 'အမှာ သိမ်းပြီး'),
  ('employee.order_edit_error', 'my', 'အမှာအသေးစိတ်ကို စစ်ပြီး ထပ်ကြိုးစားပါ'),
  ('print.print_all', 'my', 'ငွေလက်ခံနှင့် အိတ်တံဆိပ် ထုတ်မည်')
ON CONFLICT (key, locale) DO UPDATE
SET value = EXCLUDED.value;
